### ISSUE TITLE
Edit/Delete Feature for users, NGOs, and companies.

### ISSUE THREAD

**Issue by rarjun19** [Prof-Raj-Reddy-Center/BADAL#13]

**Comment by rarjun19** [comment]
The current status is as follows:

1. **Company** -> _Edit_: Not Working; _Delete_: Not Working
2. **NGO** -> _Edit_: Not Working; _Delete_: Working
3. **Projects** -> _Edit_: Not Working; _Delete_: Not Working
4. **Teams** -> _Edit_: Not Working (500 error); _Delete_: Working
5. **User** -> _Edit_: Not Working; _Delete_: Not Working

**Comment by Durga-Bhavani-Gunnam** [comment]
Updated Status:

1. Company -> Edit: Not Working; Delete: Working
2. NGO -> Edit: Not Working; Delete: Working
3. Projects -> Edit: Not Working; Delete: Working
4. Teams -> Edit: Working; Delete: Working
5. User -> Edit: Not Working;

**Comment by Durga-Bhavani-Gunnam** [comment]
Company -> Edit: Working; Delete: Working
NGO -> Edit: Working; Delete: Working
Projects -> Edit: Working; Delete: Working
Teams -> Edit: Working; Delete: Working
User -> Edit: Working;
